"""create inital tables

Revision ID: d5c36a0736ad
Revises: 1a451fe4a96b
Create Date: 2022-04-17 05:51:25.074126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c36a0736ad'
down_revision = '1a451fe4a96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
