"""empty message

Revision ID: dfc2648445a7
Revises: d5c36a0736ad
Create Date: 2022-04-17 05:59:47.080893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc2648445a7'
down_revision = 'd5c36a0736ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
